title: CasioCalc Dumping Ground
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

url: https://gamingwithevets.github.io

aux_links:
  "GitHub repository": "//github.com/gamingwithevets/casiocalc"

footer_content: "(c) Steveyboi/GamingWithEvets Inc. -- <a href=\"/\">gamingwithevets.github.io</a><br><b>All rights reserved</b>"

nav_sort: case_insensitive

search_enabled: false
