title: CasioCalc Dumping Ground
theme: just-the-docs
color_scheme: dark

kramdown:
  math_engine: mathjax

url: https://gamingwithevets.github.io

aux_links:
  "GitHub repository": "//github.com/gamingwithevets/casiocalc"

footer_content: "(c) Steveyboi/GamingWithEvets Inc. -- <a href=\"/\">gamingwithevets.github.io</a>"

nav_sort: case_insensitive

search_enabled: false

gh_edit_link: true
gh_edit_link_text: "View source/edit page on GitHub"
gh_edit_repository: "https://github.com/gamingwithevets/casiocalc"
gh_edit_branch: "main"
gh_edit_view_mode: "blob"
